# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ruby-serverless-demo
# app and org for use with dashboard.serverless.com
app: ruby-serverless
org: thermanowicz


frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  stage: prod
  region: eu-central-1
  httpApi:
    name: ruby-sls-api
    metrics: true
  iam:
    role: arn:aws:iam::901978288702:role/SyncLambda


# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  hello:
    handler: handler.hello
    memorySize: 512
    timeout: 10
    tracing: Active
    events:
      - httpApi:
          path: /hello
          method: get
  goodbye:
    handler: handler.bye
    memorySize: 512
    timeout: 10
    tracing: Active
    events:
      - httpApi:
          path: /bye
          method: get
  fake_user:
    handler: handler.rand_user
    memorySize: 512
    timeout: 10
    tracing: Active
    provisionedConcurrency: 3
    events:
      - httpApi:
          path: /fake-user
          method: get
  test_func:
    handler: handler.testing
    memorySize: 512
    timeout: 10
    tracing: Active
    events:
      - httpApi:
          path: /testing
          method: get


plugins:
  - serverless-ruby-layer
